import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from tensorboard.backend.event_processing import event_accumulator
import json
from datetime import datetime

def load_comparison_df(path: Path) -> pd.DataFrame:
	return pd.read_csv(path)


def plot_comparison_dfs(comparison_df_paths: list[Path], output_path: Path | None = None, labels: list[str] | None = None) -> dict[str, plt.Figure]:
	sns.set_theme(style="whitegrid", context="talk")

	if not comparison_df_paths:
		raise ValueError("No comparison.df files were provided")

	source_order = [labels[index] if labels and index < len(labels) else path.stem for index, path in enumerate(comparison_df_paths)]
	plot_palette = dict(zip(source_order, sns.color_palette("deep", len(source_order))))

	frames = []
	for index, path in enumerate(comparison_df_paths):
		comparison_df = load_comparison_df(path).copy()
		comparison_df["source"] = source_order[index]
		frames.append(comparison_df)

	combined = pd.concat(frames, ignore_index=True)
	figures: dict[str, plt.Figure] = {}

	for figure_key, x_col, title, xlabel in [
		("step", "test_step", "Comparison Accuracy Across Test Step", "Test Step"),
		("time", "test_time_s", "Comparison Accuracy Across Test Time", "Test Time (s)"),
	]:
		fig, ax = plt.subplots(figsize=(15, 10))
		print(x_col, combined[x_col])
		sns.lineplot(
			data=combined.sort_values(x_col),
			x=x_col,
			y="acc_ratio",
			hue="source",
			hue_order=source_order,
			palette=plot_palette,
			linewidth=6,
			marker=None,
			ax=ax,
		)
		ax.axhline(1.0, color="black", linestyle="--", linewidth=2.5, alpha=0.7)
		ax.set_xlabel(xlabel, fontsize=32)
		ax.set_ylabel("Acc_test / Acc_train", fontsize=32)
		ax.legend(fontsize=20)
		ax.grid(True, alpha=0.3)
		ax.tick_params(axis="both", which="major", labelsize=32)
		ax.set_title(title, fontsize=36, pad=20, weight="bold")
		fig.tight_layout()
		figures[figure_key] = fig

	if output_path is not None:
		output_path.mkdir(parents=True, exist_ok=True)
		figures["step"].savefig(output_path / "comparison_acc_step.svg", bbox_inches="tight")
		figures["time"].savefig(output_path / "comparison_acc_time.svg", bbox_inches="tight")

	return figures


def main():
	parser = argparse.ArgumentParser(description="Plot TensorBoard scalars with seaborn.")
	parser.add_argument(
		"--comparison_csvs",
		type=Path,
		nargs="+",
		required=True,
		help="Paths to comparison .df files generated by plot_from_tf_events.py.",
	)
	parser.add_argument(
		"--output_dir",
		type=Path,
		default=Path("comparison_plots"),
		help="Directory to save the generated comparison plots.",
	)

	parser.add_argument(
		"--labels",
		nargs="+",
		help="Labels for each comparison dataset.",
	)


	args = parser.parse_args()
	plot_comparison_dfs(args.comparison_csvs, output_path=args.output_dir, labels=args.labels)

if __name__ == "__main__":
	main()
